### ISSUE TITLE
GPU memory stacks.

### ISSUE THREAD

**Issue by YeonjeeJung** [uchidalab/softmaxgradient-lrp#1]
Hi. 

In your code, the analyzer classes are made with target id, and make graph, and do analyze with graph.

Since images have different target ids, I have to make graph for each target ids.

But in that case, the GPU memory stacks, so it stops in some iterations.

How did you implemented Maximal Patch Masking task?

Can you share code?

Thanks.

**Comment by biwana** [comment]
What I did to get around this issue is I analyzed each class separately and used K.clear_session() to reset the graph to clear the memory (without having to reload the script/data).

It's not the most elegant approach, but it seems to work fine for now.

**Comment by YeonjeeJung** [comment]
Okay.. that would work

Thank you!
